######################## default configuration ####################
baseURL = "https://retoodermatt.com"
<<<<<<< Updated upstream
title   = "Reto Odermatt"

DefaultContentLanguage = "en"

theme = "novela_v2"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.



GoogleAnalytics = "matomo.rfoo.ch"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
#enableMissingTranslationPlaceholders = false
#disableRSS     = false
#disableSitemap = false
#disable404     = false
#disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:day/:title/"

[author]
  name = "Reto Odermatt"


[params]
  dateformShort   = "2 Jan "
  dateform        = "Monday, 2. January 2006"
  dateformfull    = "Mon 2 Jan 2006 15:04 GMT"
  dateformNum = "02.01.2006"

  # Metadata mostly used in document's head
  description = "Just some site"
  keywords = "retoodermatt, reto"
  images = [""]

  homeSubtitle = "Personal Website"

  #Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/rfoo/retoodermattv2/commit/"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

 [params.categories] 
  categories = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]

  [params.logo]
    logoText     = ">"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/retoodermatt"

  [[params.social]]
    name = "github"
    url  = "https://github.com/rfoo"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/rfoo"
 

#
#[languages]
#  [languages.en]
#    subtitle  = ""
#    weight    = 1
#    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
#
#  [languages.de]
#    subtitle  = ""
#    weight    = 2
#    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"


=======
title = "Reto Odermatt"
theme = "twentytwenty"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "1"



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.main]]
name = "Sample Page"
URL = "sample-page"
weight = 5

# only desktop menu
[[menu.desktop]]
name = "Contact"
URL = "contact"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "This is meta description"
author = "reto"


# banner
[params.banner]
heading = "Welcome"
image = "images/2020-landscape-1-2.png"

# blog
[params.blog]
heading = "The premier destination for modern art in Northern Sweden. Open from 10 AM to 6 PM every day during the summer months."

# call to action
[params.call_to_action]
enable = false
title = "Contact us for more information."
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "Contact Us"
button_url = "contact"

# gallery
[params.gallery]
enable = true

  [[params.gallery.gallery_item ]]
  image = "images/2020-square-2.png"
  
  [[params.gallery.gallery_item ]]
  image = "images/2020-square-1.png"


# footer
[params.footer]
#title = "About This Site"
#content = "This may be a good place to introduce yourself and your site or include some credits."
#address = "123 Main Street <br> New York, NY 10001"
#hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
copyright = "Copyright &copy; 2020 by [reto](https://retoodermatt.com)"

############################# social site ########################
[params.social]
yelp = "#"
facebook = "#"
twitter = "#"
instagram = "#"
email = "#"
>>>>>>> Stashed changes
