baseURL = "https://retoodermatt.com"
title   = "Reto Odermatt"

DefaultContentLanguage = "en"

theme = "2019"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.



GoogleAnalytics = "matomo.rfoo.ch"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Reto Odermatt"

[blackfriday]
  hrefTargetBlank = true


[params]
  dateformShort   = "2 Jan "
  dateform        = "Monday, 2. January 2006"
  dateformfull    = "Mon 2 Jan 2006 15:04:05 EST"

  # Metadata mostly used in document's head
  description = "Just some site"
  keywords = "retoodermatt, reto"
  images = [""]

 [params.categories] 
  categories = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]


  homeSubtitle = "Personal Website"

   Prefix of link to the git commit detail page. GitInfo must be enabled.
   gitUrl = "https://github.com/rfoo/retoodermattv2"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  [params.logo]
    logoText     = ">"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/retoodermatt"

  [[params.social]]
    name = "github"
    url  = "https://github.com/rfoo"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/rfoo"
 


[languages]
  [languages.en]
    subtitle  = ""
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.de]
    subtitle  = ""
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
