
[build]
command = "hugo"
publish = "public"

[context.deploy-preview]
command = "hugo"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54.0"

[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

    # CSP Policy
    Content-Security-Policy = "base-uri 'self'; default-src 'self'; style-src 'self' 'unsafe-inline' matomo.rfoo.ch fonts.googleapis.com cdnjs.cloudflare.com; script-src 'self' identity.netlify.com cdnjs.cloudflare.com matomo.rfoo.ch; font-src 'self' fonts.googleapis.com ; img-src 'self' cdnjs.cloudflare.com matomo.rfoo.ch ; object-src 'none'; frame-ancestors 'none'; upgrade-insecure-requests; report-uri https://reto.report-uri.com/r/d/csp/enforce; report-to groupname"
    # COMMENT: Multi-key header rules are expressed with multi-line strings
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
