
[build]
  command = "hugo --gc --minify"
  publish = "public"

[context.deploy-preview]
 command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.53"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.53"