
[build]
command = "hugo"
publish = "public"

[context.deploy-preview]
command = "hugo"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54.0"

[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

    # CSP Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' identity.netlify.com cdnjs.cloudflare.com matomo.rfoo.ch; style-src 'self' unpkg.com cdnjs.cloudflare.com; img-src 'self' cdnjs.cloudflare.com matomo.rfoo.ch w3.org; font-src 'self' cdnjs.cloudflare.com matomo.rfoo.ch; connect-src 'self'; object-src 'self'; child-src 'self'; frame-src 'self'; frame-ancestors 'none'; report-uri https://reto.report-uri.com/r/d/csp/enforce"
    Feature-Policy = "vibrate none"
    Feature-Policy = "vibrate none"
    Referrer-Policy = "strict-origin"
    # COMMENT: Multi-key header rules are expressed with multi-line strings
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
