
[build]
  command = "hugo"
  publish = "public"

[context.deploy-preview]
command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.53"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.53"